export enum ServiceTypes {
    ROOMS_SERVICE = 'ROOMS_SERVICE',
    ROOM_USERS_MANAGER_SERVICE = 'ROOM_USERS_MANAGER_SERVICE',
    USERS_SERVICE = 'USERS_SERVICE',
    MESSAGE_GENERATOR_SERVICE = 'MESSAGE_GENERATOR_SERVICE',
    AUTH_SERVICE = 'AUTH_SERVICE',
}